name: lux_chain
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.2
  http: ^1.2.1
  intl: ^0.19.0
  fl_chart: ^0.67.0
  firebase_core: ^2.30.1
  firebase_storage: ^11.7.4
  google_sign_in: ^6.2.1
  url_launcher: ^6.2.6
  dotted_border: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
  
  fonts:
   - family: Bebas
     fonts: 
       - asset: assets/fonts/BebasNeue-Regular.ttf
  
   - family: Inter
     fonts: 
       - asset: assets/fonts/Inter-VariableFont_slnt,wght.ttf
